version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: regulagse_postgres
    restart: always
    environment:
      POSTGRES_USER: regulagse_user
      POSTGRES_PASSWORD: regulagse_pass
      POSTGRES_DB: regulagse_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: